name: Bug Report
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug"]
projects: []
assignees:
  - Erallie
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues and bugs and have not found the same bug I experienced.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      value: "Tell us what happened."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      value: |
          1. Go to '...'
          2. Click on '...'
          3. Scroll down to '...'
          4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      value: "Tell us what you expected."
    validations:
      required: true
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: input
    id: platform
    attributes:
      label: Platform
      description: What platform are you experiencing this bug on?
      value: "e.g. iOS/Android/Windows/MacOS/Linux"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Plugin version
      description: What is the version number of the plugin you are experiencing this bug on?
      value: "e.g. 1.0.22"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      value: "Type here"
    validations:
      required: false
