name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request] "
labels: ["enhancement"]
projects: []
assignees:
  - Erallie
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues and feature requests and have not found anything similar to what I'm requesting.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "It would be really nice if..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "I've tried X and Y solution, and it didn't work as well because..."
    validations:
      required: false
  - type: upload
    id: screenshots
    attributes:
      label: Upload screenshots
      description: If applicable, add any screenshots that may help us understand your request.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: "Type here"
    validations:
      required: false
